#!/bin/bash

set -eu

export PATH=$(dirname $0 | xargs readlink -f)/dcm2niix/usr/bin:$PATH
echo PATH=$PATH
failed=

echo "I: dcm2niix version $(dcm2niix | head -n 1)"
for d in dcm_qa*; do
	cd "$d"
	echo "I: Running tests under $d"
	./batch.sh || failed+="$d "
	cd ..
done

if [ ! -z "$failed" ]; then
    echo "E: Tests in following batteries have failed: $failed"
	exit 1
else
	echo "I: All tests seems to pass."
fi
